spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    shard1:
      url: jdbc:h2:mem:shard1;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      driver-class-name: org.h2.Driver
      username: sa
      password:
    shard2:
      url: jdbc:h2:mem:shard2;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      driver-class-name: org.h2.Driver
      username: sa
      password:
    shard3:
      url: jdbc:h2:mem:shard3;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      driver-class-name: org.h2.Driver
      username: sa
      password: