# application-postgres.yml
app:
  datasource:
    shard-alpha:
      jdbcUrl: jdbc:postgresql://${SHARD_ALPHA_HOST:localhost}:5432/shard_alpha
      username: ${SHARD_DB_USERNAME}
      password: ${SHARD_DB_PASSWORD}
      driverClassName: org.postgresql.Driver

    shard-beta:
      jdbcUrl: jdbc:postgresql://${SHARD_BETA_HOST:localhost}:5432/shard_beta
      username: ${SHARD_DB_USERNAME}
      password: ${SHARD_DB_PASSWORD}
      driverClassName: org.postgresql.Driver

    shard-gamma:
      jdbcUrl: jdbc:postgresql://${SHARD_GAMMA_HOST:localhost}:5432/shard_gamma
      username: ${SHARD_DB_USERNAME}
      password: ${SHARD_DB_PASSWORD}
      driverClassName: org.postgresql.Driver
