spring:
  h2:
    console:
      enabled: true
      path: /h2-console
app:
  datasource:
    shard-alpha:
      jdbc-url: jdbc:h2:mem:shard-alpha;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
    shard-beta:
      jdbc-url: jdbc:h2:mem:shard-beta;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
    shard-gamma:
      jdbc-url: jdbc:h2:mem:shard-gamma;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver